apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3  # Three identical replicas
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        track: stable
    spec:
      containers:
      - name: app
        image: nginx:alpine  
        env:
        - name: APP_NAME
          value: "MyApp"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5