apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    
    http {
      upstream app_servers {
        server app:3000;  # Kubernetes service name
        # Round-robin is default in nginx
      }
      
      server {
        listen 8080;
        
        location / {
          proxy_pass http://app_servers;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          
          # Add this to see which pod handled the request
          add_header X-Pod-Name $upstream_addr always;
        }
      }
    }