apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 3000
    targetPort: 3000
    # Expose on NodePort 30001 so you can curl localhost:30001
    nodePort: 30001
  type: NodePort